syms lambda mu real;
syms F11 F12 F13...
    F21 F22 F23...
    F31 F32 F33 real;
F = [F11 F12 F13;...
    F21 F22 F23;...
    F31 F32 F33...
    ];
C = (F')*F;
E = (1/2) * (C-eye(3,3));  % Green Strain Tensor
epsilon =  (1/2) * (F' + F ) - eye(3,3); % Cauchy Strain Tensor

% Saint Venant Kirchoff Strain energy function
psi_svk = (1/2) * lambda* trace(E)^2 +...
    mu * trace(E*E);

% Compressible Linear Elasticity strain energy funciton
psi_lin = (1/2) * lambda* trace(epsilon)^2 +...
    mu * trace(epsilon*epsilon);
