function P = fem_compute_P_nh(F11,F12,F13,F21,F22,F23,F31,F32,F33,lambda,mu)
%COMPUTE_P_NH
%    P = COMPUTE_P_NH(F11,F12,F13,F21,F22,F23,F31,F32,F33,LAMBDA,MU)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    06-Jul-2016 17:01:10

t2 = F11.*F22.*F33;
t3 = F12.*F23.*F31;
t4 = F13.*F21.*F32;
t8 = F11.*F23.*F32;
t9 = F12.*F21.*F33;
t10 = F13.*F22.*F31;
t5 = t2+t3+t4-t8-t9-t10;
t6 = F22.*F33;
t7 = t6-F23.*F32;
t11 = 1.0./t5;
t12 = log(t5);
t13 = F21.*F33;
t14 = t13-F23.*F31;
t15 = F21.*F32;
t16 = t15-F22.*F31;
t17 = F12.*F33;
t18 = t17-F13.*F32;
t19 = F11.*F33;
t20 = t19-F13.*F31;
t21 = F11.*F32;
t22 = t21-F12.*F31;
t23 = F12.*F23;
t24 = t23-F13.*F22;
t25 = F11.*F23;
t26 = t25-F13.*F21;
t27 = F11.*F22;
t28 = t27-F12.*F21;
P = reshape([F11.*mu-mu.*t7.*t11+lambda.*t7.*t11.*t12,F21.*mu+mu.*t11.*t18-lambda.*t11.*t12.*t18,F31.*mu-mu.*t11.*t24+lambda.*t11.*t12.*t24,F12.*mu+mu.*t11.*t14-lambda.*t11.*t12.*t14,F22.*mu-mu.*t11.*t20+lambda.*t11.*t12.*t20,F32.*mu+mu.*t11.*t26-lambda.*t11.*t12.*t26,F13.*mu-mu.*t11.*t16+lambda.*t11.*t12.*t16,F23.*mu+mu.*t11.*t22-lambda.*t11.*t12.*t22,F33.*mu-mu.*t11.*t28+lambda.*t11.*t12.*t28],[3,3]);
