function Kab = fem_compute_K_lin(Ga1,Ga2,Ga3,Gb1,Gb2,Gb3,lambda,mu)
%COMPUTE_K_LIN
%    KAB = COMPUTE_K_LIN(GA1,GA2,GA3,GB1,GB2,GB3,LAMBDA,MU)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    06-Jul-2016 15:20:42

t2 = Ga3.*Gb3.*mu;
t3 = mu.*2.0;
t4 = lambda+t3;
t5 = Ga1.*Gb1.*mu;
t6 = Ga2.*Gb2.*mu;
Kab = reshape([t2+t6+Ga1.*Gb1.*t4,Ga2.*Gb1.*lambda+Ga1.*Gb2.*mu,Ga3.*Gb1.*lambda+Ga1.*Gb3.*mu,Ga1.*Gb2.*lambda+Ga2.*Gb1.*mu,t2+t5+Ga2.*Gb2.*t4,Ga3.*Gb2.*lambda+Ga2.*Gb3.*mu,Ga1.*Gb3.*lambda+Ga3.*Gb1.*mu,Ga2.*Gb3.*lambda+Ga3.*Gb2.*mu,t5+t6+Ga3.*Gb3.*t4],[3,3]);
